use cbindgen::{Builder, Config, Language};
use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let warning = "/* Do not modify. This code was autogenerated by bindgen. */";

    let mut config = Config::default();
    config.usize_is_size_t = true;

    Builder::new()
        .with_config(config)
        .with_language(Language::C)
        .with_crate(crate_dir)
        .with_autogen_warning(warning)
        .with_include_guard("__BINDINGS_H__")
        .generate()
        .expect("cbindgen failed to generate bindings")
        .write_to_file("bindings.h");
}
